#!/bin/bash

EXEC=""
TARGET="buildScript"
declare -a PARAMS=()

for e in "$@"; do
  TARGET="$TARGET/$e"
  if [ -x "${TARGET}.sh" ]; then
    EXEC="${TARGET}.sh"
    PARAMS=()
  elif [ -n "$EXEC" ]; then
    PARAMS+=("$e")
  fi
done

echo ">> $EXEC"
[ -n "$EXEC" ] || exit 1
exec "$EXEC" "${PARAMS[@]}"
